name: Deploy Vite App to Lightsail

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: ./pickdby-frontend

    - name: Build the app
      run: npm run build
      working-directory: ./pickdby-frontend

    - name: Upload build to Lightsail
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USER }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        source: "pickdby-frontend/dist/*"
        target: "/home/ubuntu/pickdby"
